---
deployment:
  tasks:
    - export DEPLOYPATH=/home/poseursdavenir/public_html
    - cp index.html $DEPLOYPATH
    - cp mentions_legales.html $DEPLOYPATH
    - cp style.css $DEPLOYPATH
    - cp -R images $DEPLOYPATH