---
deployment:
  tasks:
    - export DEPLOYPATH=/home/poseursdavenir/public_html
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp mentions_legales.html $DEPLOYPATH
    - /bin/cp style.css $DEPLOYPATH
    - /bin/cp -R images $DEPLOYPATH